// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash pgtype.Text
	Deleted   pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    pgtype.Date
	UpdatedAt    pgtype.Date
}
