// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
insert into refresh_tokens (user_id, token_hash)
values($1, $2)
returning id, created_at
`

type CreateTokenParams struct {
	UserID    pgtype.UUID
	TokenHash pgtype.Text
}

type CreateTokenRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error) {
	row := q.db.QueryRow(ctx, createToken, arg.UserID, arg.TokenHash)
	var i CreateTokenRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, name, password_hash)
values($1, $2, $3)
returning id, name, created_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
update refresh_tokens
set deleted = true
where token_hash = $1 and user_id = $2 and deleted is false
`

type DeleteTokenParams struct {
	TokenHash pgtype.Text
	UserID    pgtype.UUID
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.TokenHash, arg.UserID)
	return err
}

const getProfile = `-- name: GetProfile :one
select id, email, name, created_at from users
where id = $1
`

type GetProfileRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Date
}

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenForUpdate = `-- name: GetTokenForUpdate :one
select token_hash, user_id, deleted from refresh_tokens
where token_hash = $1 and deleted is false for update
`

type GetTokenForUpdateRow struct {
	TokenHash pgtype.Text
	UserID    pgtype.UUID
	Deleted   pgtype.Bool
}

func (q *Queries) GetTokenForUpdate(ctx context.Context, tokenHash pgtype.Text) (GetTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTokenForUpdate, tokenHash)
	var i GetTokenForUpdateRow
	err := row.Scan(&i.TokenHash, &i.UserID, &i.Deleted)
	return i, err
}
