// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
insert into refresh_tokens (user_id, token_hash)
values($1, $2)
`

type CreateTokenParams struct {
	UserID    pgtype.UUID
	TokenHash pgtype.Text
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken, arg.UserID, arg.TokenHash)
	return err
}

const createUser = `-- name: CreateUser :one
insert into users (email, name, password_hash)
values($1, $2, $3)
returning id, name, created_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
update refresh_tokens
set deleted = true
where token_hash = $1 and user_id = $2 and deleted is false
`

type DeleteTokenParams struct {
	TokenHash pgtype.Text
	UserID    pgtype.UUID
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.TokenHash, arg.UserID)
	return err
}

const fetchPassword = `-- name: FetchPassword :one
select id, email, password_hash from users
where email = $1
`

type FetchPasswordRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) FetchPassword(ctx context.Context, email string) (FetchPasswordRow, error) {
	row := q.db.QueryRow(ctx, fetchPassword, email)
	var i FetchPasswordRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const fetchProfile = `-- name: FetchProfile :one
select id, email, password_hash, name, created_at from users
where id = $1
`

type FetchProfileRow struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Date
}

func (q *Queries) FetchProfile(ctx context.Context, id pgtype.UUID) (FetchProfileRow, error) {
	row := q.db.QueryRow(ctx, fetchProfile, id)
	var i FetchProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenForUpdate = `-- name: GetTokenForUpdate :one
select token_hash, user_id, deleted from refresh_tokens
where token_hash = $1 and deleted is false for update
`

type GetTokenForUpdateRow struct {
	TokenHash pgtype.Text
	UserID    pgtype.UUID
	Deleted   pgtype.Bool
}

func (q *Queries) GetTokenForUpdate(ctx context.Context, tokenHash pgtype.Text) (GetTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTokenForUpdate, tokenHash)
	var i GetTokenForUpdateRow
	err := row.Scan(&i.TokenHash, &i.UserID, &i.Deleted)
	return i, err
}
