FROM golang:1.27.0-trixie AS builder

WORKDIR /app

COPY ./svc/gateway/go.mod ./

COPY pkg/go.mod pkg/go.sum ./pkg/
COPY proto/go.mod proto/go.sum ./proto/
COPY svc/gateway/go.mod ./svc/gateway/

RUN go work init ./pkg ./proto ./svc/gateway

RUN go mod download

COPY pkg/ ./pkg/
COPY proto/ ./proto/
COPY svc/gateway/ ./svc/gateway/

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o /out/gateway \
    ./svc/gateway


FROM alpine:3.20


COPY --from=builder /out/gateway ./gateway

ENTRYPOINT ["./gateway"]
