FROM golang:1.27.0 AS builder
WORKDIR /app

COPY pkg/go.mod pkg/go.sum ./pkg/
COPY proto/go.mod proto/go.sum ./proto/
COPY svc/reg/go.mod svc/reg/go.sum ./svc/reg/

RUN go work init ./pkg ./proto ./svc/reg

RUN go mod download

COPY pkg/ ./pkg/
COPY proto/ ./proto/
COPY svc/reg/ ./svc/reg/

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o /out/reg \
    ./svc/reg

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/reg ./reg
ENTRYPOINT ["./reg"]
