// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateEvent = `-- name: UpdateEvent :batchexec
update events
set event_type = $2
where id = $1
`

type UpdateEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateEventParams struct {
	ID        pgtype.UUID
	EventType EventType
}

func (q *Queries) UpdateEvent(ctx context.Context, arg []UpdateEventParams) *UpdateEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.EventType,
		}
		batch.Queue(updateEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateEventBatchResults{br, len(arg), false}
}

func (b *UpdateEventBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
