// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventType string

const (
	EventTypePaymentCompleted   EventType = "payment_completed"
	EventTypePaymentPending     EventType = "payment_pending"
	EventTypePaymentFailed      EventType = "payment_failed"
	EventTypePaymentChargedback EventType = "payment_chargedback"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type OrderStatus string

const (
	OrderStatusCreated   OrderStatus = "created"
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusCompleted OrderStatus = "completed"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Event struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	Status    OrderStatus
	EventType EventType
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Item struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Order struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TotalPrice pgtype.Numeric
	Status     OrderStatus
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type OrderItem struct {
	OrderID pgtype.UUID
	ItemID  pgtype.UUID
}
