// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
update orders
set status = 'cancelled'
where id = $1 and user_id = $2
`

type CancelOrderParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) error {
	_, err := q.db.Exec(ctx, cancelOrder, arg.ID, arg.UserID)
	return err
}

const createOrder = `-- name: CreateOrder :one
insert into orders (user_id, total_price)
values ($1, $2)
returning id, total_price, status
`

type CreateOrderParams struct {
	UserID     pgtype.UUID
	TotalPrice pgtype.Numeric
}

type CreateOrderRow struct {
	ID         pgtype.UUID
	TotalPrice pgtype.Numeric
	Status     OrderStatus
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalPrice)
	var i CreateOrderRow
	err := row.Scan(&i.ID, &i.TotalPrice, &i.Status)
	return i, err
}

const createOrderItems = `-- name: CreateOrderItems :exec
insert into order_items (order_id, item_id)
values ($1, $2)
`

type CreateOrderItemsParams struct {
	OrderID pgtype.UUID
	ItemID  pgtype.UUID
}

func (q *Queries) CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) error {
	_, err := q.db.Exec(ctx, createOrderItems, arg.OrderID, arg.ItemID)
	return err
}

const fetchOrder = `-- name: FetchOrder :one
with item_counts as (
    select o.id as order_id, o.total_price, o.status, o.created_at,
        i.id as item_id, i.name, i.price, count(oi.item_id) as quantity
    from orders o
    left join order_items oi on o.id = oi.order_id
    left join items i on oi.item_id = i.id
    where o.id = $1 and o.user_id = $2
    group by o.id, i.id, i.name, i.price
)
select
    order_id as id,
    total_price,
    status,
    created_at,
    coalesce(
        json_agg(
            json_build_object('name', name, 'price', price, 'quantity', quantity)
            order by quantity desc
        ) filter (where item_id is not null),
        '[]'
    )::jsonb as items
from item_counts
group by order_id, total_price, status, created_at
`

type FetchOrderParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type FetchOrderRow struct {
	ID         pgtype.UUID
	TotalPrice pgtype.Numeric
	Status     OrderStatus
	CreatedAt  pgtype.Timestamp
	Items      []byte
}

func (q *Queries) FetchOrder(ctx context.Context, arg FetchOrderParams) (FetchOrderRow, error) {
	row := q.db.QueryRow(ctx, fetchOrder, arg.ID, arg.UserID)
	var i FetchOrderRow
	err := row.Scan(
		&i.ID,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.Items,
	)
	return i, err
}

const fetchUserOrders = `-- name: FetchUserOrders :many
select id, total_price, status, created_at from orders
where user_id = $1
order by created_at desc
limit $2
offset $3
`

type FetchUserOrdersParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type FetchUserOrdersRow struct {
	ID         pgtype.UUID
	TotalPrice pgtype.Numeric
	Status     OrderStatus
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) FetchUserOrders(ctx context.Context, arg FetchUserOrdersParams) ([]FetchUserOrdersRow, error) {
	rows, err := q.db.Query(ctx, fetchUserOrders, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchUserOrdersRow
	for rows.Next() {
		var i FetchUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectOrderForUpdate = `-- name: SelectOrderForUpdate :one
select id, user_id, status from orders
where id = $1 and user_id = $2 for update
`

type SelectOrderForUpdateParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type SelectOrderForUpdateRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Status OrderStatus
}

func (q *Queries) SelectOrderForUpdate(ctx context.Context, arg SelectOrderForUpdateParams) (SelectOrderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, selectOrderForUpdate, arg.ID, arg.UserID)
	var i SelectOrderForUpdateRow
	err := row.Scan(&i.ID, &i.UserID, &i.Status)
	return i, err
}
