syntax = "proto3";

package user.v1;
option go_package = "proto/out/user/v1;userv1";

service UserService {
    rpc RegisterUser(RegisterUserRequest) returns(RegisterUserResponse);
    rpc LoginUser(LoginUserRequest) returns(LoginUserResponse);
    rpc GetProfile(GetProfileRequest) returns(GetProfileResponse);
    rpc Logout(LogoutRequest) returns(LogoutResponse);
}

message RegisterUserRequest {
    string email = 1;
    string password = 2;
    string name = 3;
}

message RegisterUserResponse {
    string response = 1;
}

message GetProfileRequest {
    string jwt = 1;
}

message GetProfileResponse {
    string id = 1;
    string email = 2;
    string name = 3;
    string date = 4;
}

message LoginUserRequest {
    string email = 1;
    string password = 2;
}

message LoginUserResponse {
    string access = 1;
    string refresh = 2;
    string type = 3;
}

message LogoutRequest {
    string refresh_token = 1;
}

message LogoutResponse {
    string response = 1;
}
