// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   pgtype.UUID
	Name string
}

type Item struct {
	ID          pgtype.UUID
	Name        string
	Price       pgtype.Numeric
	Description pgtype.Text
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
}

type ItemsCategory struct {
	ItemID     pgtype.UUID
	CategoryID pgtype.UUID
}
