// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getItem = `-- name: GetItem :one
select i.id, i.name, i.description, c.name as category_name from items i
join items_categories ic on i.id = ic.item_id
join categories c on ic.category_id = c.id
where i.id = $1
`

type GetItemRow struct {
	ID           pgtype.UUID
	Name         string
	Description  pgtype.Text
	CategoryName string
}

func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CategoryName,
	)
	return i, err
}

const getItems = `-- name: GetItems :many
select i.id, i.name, i.description, c.name as category_name from items i
join items_categories ic on i.id = ic.item_id
join categories c on ic.category_id = c.id
where c.name = any($1)
group by i.id
`

type GetItemsRow struct {
	ID           pgtype.UUID
	Name         string
	Description  pgtype.Text
	CategoryName string
}

func (q *Queries) GetItems(ctx context.Context, categories []string) ([]GetItemsRow, error) {
	rows, err := q.db.Query(ctx, getItems, categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsRow
	for rows.Next() {
		var i GetItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
